apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: main-pool
  namespace: kube-system
spec:
  serviceSelector:
    matchLabels:
      run: test-nginx
  cidrs:
  - cidr: "172.16.0.100/30"