apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: main-pool
  namespace: kube-system
spec:
  serviceSelector:
    matchLabels:
      cilium.io/ingress: "true"
  cidrs:
  - cidr: "192.168.50.100/30"