
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-traefik
  namespace: default
spec:
  selector:
    matchLabels:
      run: test-traefik
  replicas: 3
  template:
    metadata:
      labels:
        run: test-traefik
    spec:
      containers:
      - name: test-traefik
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: test-traefik
  namespace: default
  labels:
    run: test-traefik
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: test-traefik
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik-ingress
  namespace: default
spec:
  ingressClassName: traefik
  rules:
  - http:
      paths:
      - backend:
          service:
            name: test-traefik
            port:
              number: 80
        path: /
        pathType: Prefix